/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project01;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.*;





/**
 *
 * @author 1
 */
public class G14Manage extends javax.swing.JFrame {


    /**
     * Creates new form create
     */
    public G14Manage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        balanceField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        createButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        modifyButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        adminRadioButton = new javax.swing.JRadioButton();
        specialRadioButton = new javax.swing.JRadioButton();
        commonRadioButton = new javax.swing.JRadioButton();
        PasswordField = new javax.swing.JPasswordField();
        approveRadioButton = new javax.swing.JRadioButton();
        unapproveRadioButton = new javax.swing.JRadioButton();
        finishButton = new javax.swing.JButton();
        displayButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("User Management");

        jLabel2.setText("Image Editing System");

        jLabel3.setText("ID:");

        jLabel4.setText("Name:");

        jLabel5.setText("Password:");

        jLabel6.setText("User Type:");

        jLabel7.setText("Status:");

        jLabel8.setText("Current Balance:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Password", "User Type", "Time Created", "User Status", "Current Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        modifyButton.setText("Modify");
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        adminRadioButton.setText("Admin");
        adminRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminRadioButtonActionPerformed(evt);
            }
        });

        specialRadioButton.setText("Special");
        specialRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialRadioButtonActionPerformed(evt);
            }
        });

        commonRadioButton.setText("Common");
        commonRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonRadioButtonActionPerformed(evt);
            }
        });

        approveRadioButton.setText("Approve");
        approveRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveRadioButtonActionPerformed(evt);
            }
        });

        unapproveRadioButton.setText("Unapprove");
        unapproveRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unapproveRadioButtonActionPerformed(evt);
            }
        });

        finishButton.setText("Finish");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        displayButton.setText("Display");
        displayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(124, 124, 124))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(108, 108, 108)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(89, 89, 89)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(idField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                        .addComponent(nameField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PasswordField, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(adminRadioButton)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(specialRadioButton)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(commonRadioButton))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(13, 13, 13)
                                                    .addComponent(balanceField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addComponent(approveRadioButton)
                                            .addGap(18, 18, 18)
                                            .addComponent(unapproveRadioButton)))))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(227, 227, 227))))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(displayButton)
                .addGap(36, 36, 36)
                .addComponent(createButton)
                .addGap(76, 76, 76)
                .addComponent(modifyButton)
                .addGap(89, 89, 89)
                .addComponent(deleteButton)
                .addGap(0, 182, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(finishButton)
                        .addGap(73, 73, 73)
                        .addComponent(jButton2)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(adminRadioButton)
                    .addComponent(specialRadioButton)
                    .addComponent(commonRadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(approveRadioButton)
                    .addComponent(unapproveRadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(balanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(modifyButton)
                    .addComponent(deleteButton)
                    .addComponent(displayButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(finishButton))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
       
        if(!(idField.getText().trim().equals("")||nameField.getText().trim().equals("")
                ||PasswordField.getText().trim().equals("")||balanceField.getText().trim().equals(""))){
            
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy.MM.dd G 'at' HH:mm:ss z");
        String time = cal.getTime().toString();
        
        String userid = this.idField.getText(); 
        String userName = this.nameField.getText();
        String passWord = this.PasswordField.getText();
        String userStatus = "";
        String Balance =this.balanceField.getText();
        String userType="";
        
        

            if(adminRadioButton.isSelected()) {
                userType = "a"+userType;
            }else if(specialRadioButton.isSelected()) {
                userType = "s"+userType;
            }else if(commonRadioButton.isSelected()){
                userType = "c"+userType;
            }
            

        if(approveRadioButton.isSelected()) {
         userStatus = "approve"+userStatus;
        }else if(unapproveRadioButton.isSelected()) {
        userStatus = "unapprove"+userStatus;
        }
        
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{userid,userName,passWord,userType,time,userStatus,Balance});
        
        }else{
            JOptionPane.showMessageDialog(rootPane,"Please enter the remain information!");
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
                    G14AUserInfo aform= new G14AUserInfo();
                    aform.setVisible(true); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void adminRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminRadioButtonActionPerformed
       if(adminRadioButton.isSelected()) 
        specialRadioButton.setSelected(false);
        commonRadioButton.setSelected(false);
        String userType = "a";
    }//GEN-LAST:event_adminRadioButtonActionPerformed

    private void specialRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialRadioButtonActionPerformed
        if(specialRadioButton.isSelected()) 
        adminRadioButton.setSelected(false);
        commonRadioButton.setSelected(false);
        String userType = "s";
    }//GEN-LAST:event_specialRadioButtonActionPerformed

    private void commonRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commonRadioButtonActionPerformed
      if(commonRadioButton.isSelected()) 
        specialRadioButton.setSelected(false);
        adminRadioButton.setSelected(false);
        String userType = "c";
    }//GEN-LAST:event_commonRadioButtonActionPerformed

    private void approveRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveRadioButtonActionPerformed
        if(approveRadioButton.isSelected()) 
        unapproveRadioButton.setSelected(false);
        String userStatus = "approve";
    }//GEN-LAST:event_approveRadioButtonActionPerformed

    private void unapproveRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unapproveRadioButtonActionPerformed
        if(unapproveRadioButton.isSelected()) 
        approveRadioButton.setSelected(false);
        String userStatus = "unapprove";        
    }//GEN-LAST:event_unapproveRadioButtonActionPerformed

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow()==-1){
            if(jTable1.getRowCount()==0){
                JOptionPane.showMessageDialog(rootPane,"Table is empty!");
            }else{
                JOptionPane.showMessageDialog(rootPane, "You must select a row!");
            }
        }else{
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy.MM.dd G 'at' HH:mm:ss z");
        String time = cal.getTime().toString();
        String userid = this.idField.getText(); 
        String userName = this.nameField.getText();
        String passWord = this.PasswordField.getText();
        String userStatus = "";
        String Balance =this.balanceField.getText();
        String userType="";
        
        if(adminRadioButton.isSelected()) {
                userType = "a"+userType;
            }else if(specialRadioButton.isSelected()) {
                userType = "s"+userType;
            }else if(commonRadioButton.isSelected()){
                userType = "c"+userType;
            }
            

        if(approveRadioButton.isSelected()) {
         userStatus = "approve"+userStatus;
        }else if(unapproveRadioButton.isSelected()) {
        userStatus = "unapprove"+userStatus;
        }
        
        model.setValueAt(userid,jTable1.getSelectedRow(),0);
        model.setValueAt(userName,jTable1.getSelectedRow(),1);
        model.setValueAt(passWord,jTable1.getSelectedRow(),2);
        model.setValueAt(userType,jTable1.getSelectedRow(),3);
        model.setValueAt(time,jTable1.getSelectedRow(),4);
        model.setValueAt(userStatus,jTable1.getSelectedRow(),5);
        model.setValueAt(Balance,jTable1.getSelectedRow(),6);
        
   
        }
    }//GEN-LAST:event_modifyButtonActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
         Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy.MM.dd G 'at' HH:mm:ss z");
        String time = cal.getTime().toString();
        
        String userid = this.idField.getText(); 
        String userName = this.nameField.getText();
        String passWord = this.PasswordField.getText();
        String userStatus = "";
        String Balance =this.balanceField.getText();
        String userType="";
        
        if(adminRadioButton.isSelected()) {
                userType = "a"+userType;
            }else if(specialRadioButton.isSelected()) {
                userType = "s"+userType;
            }else if(commonRadioButton.isSelected()){
                userType = "c"+userType;
            }
            

        if(approveRadioButton.isSelected()) {
         userStatus = "approve"+userStatus;
        }else if(unapproveRadioButton.isSelected()) {
        userStatus = "unapprove"+userStatus;
        }
        
        
        
        
        
        
        try{
     //把用户信息存进文件里
            //创建高效字符输出流来给文件写入数据，创建了一个可以追加写入的FileWriter，避免了文件中之前的用户信息被覆盖
            BufferedWriter bw = new BufferedWriter(new FileWriter("user.csv",true));
            bw.write(userid+",");
            bw.write(userName+",");
            bw.write(passWord+",");


            
           
            
            bw.write(userType+",");        
            bw.write(time+",");
            bw.write(userStatus+",");
            bw.write(Balance);
            bw.newLine();
            bw.flush();
            bw.close();


            JOptionPane.showMessageDialog(rootPane,"Success!");

        }catch(IOException e){
            JOptionPane.showMessageDialog(rootPane,"Error");
            e.printStackTrace();
        }
        setVisible(false);
                    G14AUserInfo aform= new G14AUserInfo();
                    aform.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_finishButtonActionPerformed

    private void displayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayButtonActionPerformed
        try{
            BufferedReader br = new BufferedReader(new FileReader("user.csv"));
            String firstline = br.readLine().trim();
            String[]columnsName = firstline.split(",");
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setColumnIdentifiers(columnsName);
            
            
            Object[] tableLines = br.lines().toArray();
            
            for (int i = 0; i < tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(",");
                model.addRow(dataRow);
            }
            
        }catch(IOException e){
            e.printStackTrace();
        }      
    }//GEN-LAST:event_displayButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        String userStatus = "";
        String Balance =this.balanceField.getText();
        String userType="";
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        idField.setText(model.getValueAt(jTable1.getSelectedRow(),0).toString());
        nameField.setText(model.getValueAt(jTable1.getSelectedRow(),1).toString());
        PasswordField.setText(model.getValueAt(jTable1.getSelectedRow(),2).toString());
        balanceField.setText(model.getValueAt(jTable1.getSelectedRow(),6).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow()==-1){
            if(jTable1.getRowCount()==0){
                JOptionPane.showMessageDialog(rootPane,"Table is empty!");
            }else{
                JOptionPane.showMessageDialog(rootPane, "You must select a row!");
            }
        }else{
        model.removeRow(jTable1.getSelectedColumn());
        }
        
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(G14Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(G14Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(G14Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(G14Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new G14Manage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JRadioButton adminRadioButton;
    private javax.swing.JRadioButton approveRadioButton;
    private javax.swing.JTextField balanceField;
    private javax.swing.JRadioButton commonRadioButton;
    private javax.swing.JButton createButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton displayButton;
    private javax.swing.JButton finishButton;
    private javax.swing.JTextField idField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modifyButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JRadioButton specialRadioButton;
    private javax.swing.JRadioButton unapproveRadioButton;
    // End of variables declaration//GEN-END:variables
}
